name: buxbux
description: BuxBux - Personal Finance App for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  share_plus: ^10.0.2
  path_provider: ^2.1.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
